export const orders = [
  {
    id: 2,
    name: "B Set",
    curry1: "Vegetable",
    curry2: "",
    amount: 2,
    spiceLevel: 1,
    drink: "HotChai",
    complementary: "Soup and Salad",
    date: "2022-10-09",
  },
  {
    id: 1,
    name: "A Set",
    curry1: "Mutton",
    curry2: "Mutton",
    amount: 2,
    spiceLevel: 1,
    drink: "IceTea",
    complementary: "Soup and Salad",
    date: "2022-10-09",
  },
  {
    id: 2,
    name: "B Set",
    curry1: "Mutton",
    curry2: "",
    amount: 2,
    spiceLevel: 1,
    drink: "IceTea",
    complementary: "Soup and Salad",
    date: "2022-10-09",
  },
  {
    id: 4,
    name: "B Set dinner",
    curry1: "Chicken",
    curry2: "",
    amount: 2,
    spiceLevel: 1,
    drink: "HotChai",
    complementary: "Soup and Salad",
    date: "2022-10-01",
  },
  {
    id: 11,
    name: "A Set",
    curry1: "Vegetable",
    curry2: "Vegetable",
    amount: 1,
    spiceLevel: 1,
    drink: "",
    complementary: "Soup and Salad",
    date: "2022-10-05",
  },
  {
    id: 1,
    name: "A Set",
    curry1: "Vegetable",
    curry2: "Mutton",
    amount: 2,
    spiceLevel: 1,
    drink: "HotChai",
    complementary: "Soup and Salad",
    date: "2022-09-09",
  },
];
