export const items = [
  {
    id: 1,
    name: "A Set",
    curryAmount: 2,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "lunch",
    price: "990",
  },
  {
    id: 2,
    name: "B Set",
    curryAmount: 1,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "lunch",
    price: "1200",
  },
  {
    id: 3,
    name: "A Set dinner",
    curryAmount: 2,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "dinner",
    price: "990",
  },
  {
    id: 4,
    name: "B Set dinner",
    curryAmount: 1,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "dinner",
    price: "1200",
  },
  {
    id: 5,
    name: "samosa",
    curryAmount: "",
    choiceCurry: "",
    choiceDrink: "",
    complementary: "",
    category: "lunch",
    price: "200",
  },
  {
    id: 6,
    name: "A Set",
    curryAmount: 2,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "lunch",
    price: "990",
  },
  {
    id: 7,
    name: "B Set",
    curryAmount: 1,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "lunch",
    price: "1200",
  },
  {
    id: 8,
    name: "A Set dinner",
    curryAmount: 2,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "dinner",
    price: "990",
  },
  {
    id: 9,
    name: "B Set dinner",
    curryAmount: 1,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "dinner",
    price: "1200",
  },
  {
    id: 10,
    name: "samosa",
    curryAmount: "",
    choiceCurry: "",
    choiceDrink: "",
    complementary: "",
    category: "lunch",
    price: "200",
  },
  {
    id: 11,
    name: "A Set",
    curryAmount: 2,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "lunch",
    price: "990",
  },
  {
    id: 12,
    name: "B Set",
    curryAmount: 1,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "lunch",
    price: "1200",
  },
  {
    id: 13,
    name: "A Set dinner",
    curryAmount: 2,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "dinner",
    price: "990",
  },
  {
    id: 14,
    name: "B Set dinner",
    curryAmount: 1,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "dinner",
    price: "1200",
  },
  {
    id: 15,
    name: "samosa",
    curryAmount: "",
    choiceCurry: "",
    choiceDrink: "",
    complementary: "",
    category: "lunch",
    price: "200",
  },
  {
    id: 16,
    name: "A Set",
    curryAmount: 2,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "lunch",
    price: "990",
  },
  {
    id: 17,
    name: "B Set",
    curryAmount: 1,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "lunch",
    price: "1200",
  },
  {
    id: 18,
    name: "A Set dinner",
    curryAmount: 2,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "dinner",
    price: "990",
  },
  {
    id: 19,
    name: "B Set dinner",
    curryAmount: 1,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "dinner",
    price: "1200",
  },
  {
    id: 20,
    name: "samosa",
    curryAmount: "",
    choiceCurry: "",
    choiceDrink: "",
    complementary: "",
    category: "lunch",
    price: "200",
  },
  {
    id: 21,
    name: "indian set",
    curryAmount: 1,
    choiceCurry: ["Chicken", "Keema", "Mutton", "Vegetable"],
    choiceDrink: ["Lassi", "MangoLassi", "HotChai", "IceTea"],
    complementary: "Soup and Salad",
    category: "lunch",
    price: "990",
  },
];
